resolver: lts-9.0
packages:
- location: .
- location: 
    git: git@github.com:yi-editor/yi
    commit: 4bd5dc26109ade8a4f757f454fce063385cb6855
# For local hacking:
#- location: ../yi
  subdirs:
  - yi-core
  - yi-frontend-vty
  - yi-frontend-pango
  - yi-keymap-cua
  - yi-keymap-emacs
  - yi-misc-modes
  - yi-mode-haskell
  extra-dep: true


