resolver: lts-9.17
packages:
- location: .
- location:
    git: git@github.com:yi-editor/yi-rope
    commit: fc711de176aa1453cd197826c2f84a5b21c9ca51
  extra-dep: true
- location:
    git: git@github.com:yi-editor/yi
    commit: c344ffd26988a47aaaf1029f38968460cba4b695
# For local hacking:
#- location: ../yi
  subdirs:
  - yi-language
  - yi-core
  - yi-frontend-vty
  - yi-frontend-pango
  - yi-keymap-cua
  - yi-keymap-emacs
  - yi-misc-modes
  - yi-mode-haskell
  extra-dep: true


